asset_management/urls.py
from django.contrib import admin
from django.urls import path, include
from asset_master.views import *
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    # Admin
    path('admin/', admin.site.urls),

    # Asset Module
    path('asset-form/', AssetMasterPostView.as_view(), name='asset-master'),
    path('asset-list/', AssetListView.as_view(), name='asset_list'),
    path('asset-delete/', AssetMultipleDeleteView.as_view(), name='asset_delete'),
    path('asset-delete/<int:id>/', AssetMultipleDeleteView.as_view(), name='asset_delete_by_id'),
    path('asset-detail/<int:id>/', asset_detail_view, name='asset_detail'),
    path('edit-asset-detail/<int:id>/', update_asset, name='edit_asset_detail'),
    # path('edit-rent-detail/<int:id>/', update_asset, name='edit_rent_detail'),
    path('delete-asset-detail-image/', delete_image, name='delete_asset_detail_image'),
    path('asset-detail-set-availability/', set_availability, name='asset_detail_set_availability'),
    path('asset-detail-set-under-amc/', set_under_amc, name='asset_detail_set_under_amc'),
    path('asset-detail-set-asset-status/', set_asset_status, name='asset_detail_set_asset_status'),
    path('asset-list-search/', autocomplete_search, name='asset_list_search'),

    path('asset-list-search-group-wise/', autocomplete_search_group_wise, name='autocomplete_search_group_wise'),
    
    path('asset-list-acc-search/', autocomplete_acc_search, name='autocomplete_acc_search'),

    path('group-wise-asset-list/', group_wise_asset_list, name='group_wise_asset_list'),
    path('get-group-wise-asset-detail/', GetGroupWiseAssetAccessories.as_view(), name='group_wise_asset_accessories'),

    #Search analytics
    path('asset-list-search-analytics/', autocomplete_search_analytics, name='autocomplete_search_analytics'),
    path('asset-list-search-analytics-brand/', autocomplete_search_analytics_brand, name='autocomplete_search_analytics_brand'),

    path('asset-list-fix-nsn/', fixNSN, name='fix_nsn'),


    #Sold Asset   
    path('sold-list/', SoldAssetListView.as_view(), name='soldasset_list'),
    path('sold-detail/<int:id>/', sold_detail, name='sold_detail'),
    path('edit-sold-detail/', update_sold, name='edit_sold_detail'),
    path('asset-list-sold/', sold_asset, name='edit_sold_detail'),
    path('sold-asset-delete/', SoldAssetMultipleDeleteView.as_view(), name='sold_asset_delete'),


    #Analytics Asset   
    path('analytics-list/', analytics_list, name='analytics_list'),
    path('analytics-category/<str:category>/', analytics_category, name='analytics_category'),
    path('analytics-brand/<str:brand>/', analytics_brand, name='analytics_brand'),


    #Loaned Asset
    path('loan-list/', LoanListView.as_view(), name='loan_list'),
    path('loan-detail/<int:id>/', loan_detail, name='loan_detail'),
    path('edit-loan-detail/<int:id>/', update_loaned_asset, name='edit_loan_detail'),
    path('loan-form/', AssetMasterLoanPostView.as_view(), name='loan_form_post_view'),
    path('loan-asset-delete/', LoanAssetMultipleDeleteView.as_view(), name='loan_asset_delete'),


    #Rent Asset
    path('rent-list/', RentListView.as_view(), name='rent_list'),
    path('rent-detail/<int:id>/', rent_detail, name='rent_detail'),
    path('edit-rent-detail/<int:id>/', update_rented_asset, name='rent_detail'),
    path('rent-form/', AssetMasterRentPostView.as_view(), name='rent_form'),
    path('rent-asset-delete/', RentAssetMultipleDeleteView.as_view(), name='rent_asset_delete'),


    # Upload Excel
    path('upload/', upload_aaset_excel, name='upload_asset_excel'),
    path('upload-sold-asset/', upload_sold_aaset_excel, name='upload_sold_asset_excel'),
    path('upload-loan-asset/', upload_loan_aaset_excel, name='upload_loan_asset_excel'),
    path('upload-rent-asset/', upload_rent_aaset_excel, name='upload_rent_asset_excel'),
    # path('upload-warehouse/', upload_excel_warehouse, name='upload_excel_warehouse'),

    # Dashboard
    path('',home,name='home'),

    # Login & Logout
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),


    #Frogot password
    path('forgot-password/', auth_views.PasswordResetView.as_view(template_name='forgot_password.html'), name='password_reset'),
    path('password_reset_sent/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_success_msg.html'), name='password_reset_done'),
    path('password_reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_form.html'), name='password_reset_confirm'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_done.html'), name='password_reset_complete'),


    # Clone Asset
    path('clone-asset/', clone_asset, name='clone_asset'),

    #Edit comment
    path('edit-asset-detail-comment-again/', update_comment_again, name='edit_asset_detail_comment'),


    #Add to order
    path('add-to-order-asset/', add_to_order, name='add_to_order'),

    #Remove from order
    path('remove-from-order-asset/', remove_from_order, name='remove_from_order'),
    
    
    #Remove from order
    path('send-to-external-repair-asset/', asset_sent_for_external_repair, name='asset_sent_for_external_repair'),

    path('send-to-internal-repair-asset/', asset_sent_for_internal_repair, name='asset_sent_for_internal_repair'),

    # Order Module
    path('asset_management/', include('orders.urls'), name='asset_management_orders'), 

    #Warehouse Module
    # path('asset_management/', include('warehouse.urls'), name='asset_management_warehouse'), 

    #Repair Module
    path('asset_management/', include('repair_maintenance.urls'), name='asset_management_repair_maintenance'), 

    #Order Dispatch Module
    path('asset_management/', include('orderdispatch.urls'), name='asset_management_orderdispatch'), 
    
    
    #Reports
    path('asset_management/', include('reports.urls'), name='asset_management_reports'), 

    #Requiremnts
    path('asset_management/', include('requirements.urls'), name='asset_management_requirements'), 


    # Export to csv file
    path('export-to-csv/', export_to_csv, name='export_to_csv'), 

    # Export to pdf file
    path('export-to-pdf/', generate_asset_pdf, name='export_to_pdf'), 

    # Attach file to asset
    path('attach-file-to-asset/', attach_file_to_asset, name='attach_file_to_asset'), 
    path('asset-management-rented/<int:id>/', rented, name='asset_management_rented'), 
    path('asset-management-outsource/',OutsourceView.as_view(), name='asset_management_outsource'), 

    # Delete Attached file
    path('delete-attached-file/', delete_attached_file, name='delete_attached_file'), 

    # Outsource comment
    path('edit-asset-detail-comment-again-outsource/', update_comment_again_outsource, name='update_comment_again_outsource'), 
    
    path('attach-file-to-outsource/', attach_file_to_asset_outsource, name='attach_file_to_asset_outsource'), 
    
    path('delete-attached-file-outsource/', delete_attached_file_outsource, name='delete_attached_file_outsource'), 

    path('asset-delete-outsource/', AssetMultipleOutsourceDeleteView.as_view(), name='asset_delete_outsource'),




]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)


# urlpatterns += staticfiles_urlpatterns()

orders/urls.py
from django.urls import path, include
from orders.views import *

urlpatterns = [

    #Orders 
    path('all-orders-list/', cart_list_view, name='all_orders_list' ),
    # path('all-orders-list/', OrderCartList, name='all_orders_list' ),
    path('orders-form/', AssetMasterOrderPostView, name='orders_form' ),
    path('export-to-csv-order/', export_to_csv_order, name='export_to_csv'), 
    path('orders-info/<int:id>/', orders_info_view, name='orders_info_view'),
    # path('confirmed-order-list/', confirmed_orders_list, name='confirmed_orders_list'),
    path('confirmed-orders-list/', ConfirmOrderListView.as_view(), name='confirmed_order_list'),
    path('orders-form-edit/<int:id>/', orders_form_edit, name='confirmed_orders_list'),

    #Customer
    path('customer-details/<int:id>/', customer_details, name='customer_details'),
    path('add-new-customer/', AssetMasterCustomerPostView.as_view(), name='add_new_customer'),
    path('attach-file-to-customer/', attach_file_to_customer, name='attach_file_to_customer'),
    path('customer-comments/', update_comment_again_customer, name='update_comment_again_customer'),
    path('customer-form-edit/<int:id>/', customer_form_edit, name='orders_formedit' ),
    path('customer-attach-file-delete/', customer_attach_file_delete, name='customer_attach_file_delete'),

    #Export to csv order list
    path('order-cart-export-to-csv/', order_cart_export_to_csv, name='order_cart_export_to_csv'),
    path('confirmed-order-export-to-csv/', confirmed_order_export_to_csv, name='confirmed_order_export_to_csv'),

    #Auto search URL
    path('order-cart-search/', autocomplete_search_orders_cart, name='autocomplete_search_orders_cart'),
    path('confirm-order-search/', autocomplete_search_confirm_orders, name='autocomplete_search_confirm_orders'),
    
    #PDFs
    path('order-detail-pdf/', generate_order_pdf, name='generate_order_pdf'),

    #Approve Order
    path('approve-order/', approve_order, name='approve_order'),

    #Remove asset from order
    path('remove-asset-from-order/', remove_asset_from_order, name='remove_asset_from_order'),

    #Add asset to order
    path('add-asset-to-order/', add_asset_to_order, name='add_asset_to_order'),

    #Cancel Order
    path('cancel-order/', cancel_order, name='cancel_order'),

    #Order dispatch
    path('dispatch-order/', order_dispatch, name='order_dispatch'),


    path('get_data/', get_data.as_view(), name='get_data/'),

    #Alert accessory list
    path('alert-for-accessories/', LeftOutAccessoryList.as_view(), name='left_out_accessory_list'),

    #Attach file to order
    path('attach-file-to-order/', attach_file_to_order, name='attach_file_to_order'),

    #Order comment
    path('add-comment-to-order/', update_comment_again_order, name='update_comment_again_order'),


    #Order attach file delete
    path('order-attach-file-delete/', delete_attached_file_order_dispatch, name='delete_attached_file_order_dispatch'),


    #Orders History
    path('go-to-orders-history/', order_history_list, name='order_history'),
    path('go-to-orders-history-details/<int:id>/', order_history_details, name='order_history_details'),

]

orders/models.py
from django.db import models
from asset_master.models import AssetMaster 
import uuid
# from enums.order_status_enum import OrderStatus




class CustomerDetail(models.Model):
    customer = models.CharField(max_length=100, blank=True, null=True)
    completed_orders = models.CharField(max_length=100, blank=True, null=True)
    deployed_order = models.CharField(max_length=100, blank=True, null=True)
    taxed = models.CharField(max_length=100, blank=True, null=True)
    email_address = models.CharField(max_length=100, blank=True, null=True)
    department = models.CharField(max_length=100, blank=True, null=True)
    phone_number = models.CharField(max_length=100, blank=True, null=True)
    customer_revenue = models.CharField(max_length=100, blank=True, null=True)
    commercial_address = models.CharField(max_length=100, blank=True, null=True)
    category = models.CharField(max_length=100, blank=True, null=True)
    created_at = models.DateField(null=True, blank=True, default=None)
    secondary_email = models.CharField(max_length=100, blank=True, null=True)
    description = models.CharField(max_length=100, blank=True, null=True)



class CustomerAttachFile(models.Model):
    customer_id = models.ForeignKey(CustomerDetail, on_delete= models.CASCADE)
    attached_file = models.FileField(upload_to="media/", default=None, null=True, blank=True)


class CustomerComment(models.Model):
    customer_id = models.ForeignKey(CustomerDetail, on_delete= models.CASCADE)
    comment = models.CharField(max_length=100, null=True, blank=True)
    date_time = models.DateTimeField(auto_now=False, auto_now_add=False)

class OrderDetail(models.Model):
    class OrderStatus(models.IntegerChoices):
            BOOKED = 1,
            APPROVED = 2,
            CANCELLED = 3,
            DISPATCHED = 4,
    assets = models.ManyToManyField(AssetMaster, related_name='order_details', blank=True)
    # order_id = models.UUIDField(editable=False, default=uuid.uuid4)
    customer_id = models.ForeignKey(CustomerDetail, on_delete=models.SET_NULL, null=True)
    price = models.CharField(null=True, blank=True, max_length=50)
    # rent_out_date = models.DateField(null=True, blank=True)
    order_status = models.IntegerField(choices=OrderStatus.choices, default=OrderStatus.BOOKED)   
    organization = models.CharField(max_length=100, blank=True, null=True)
    # quantity = models.PositiveIntegerField(null=True, blank=True)
    remarks = models.CharField(max_length=100, null=True, blank=True)
    customer = models.CharField(max_length=100, null=True, blank=True)
    deployment_date = models.DateField(null=True, blank=True)
    return_date = models.DateField(null=True, blank=True)
    name_of_consignee = models.CharField(max_length=100, blank=True, null=True)
    invoice_number = models.CharField(max_length=100, blank=True, null=True)
    mode_of_dispatch = models.CharField(max_length=100, blank=True, null=True)
    transportation = models.CharField(max_length=100, blank=True, null=True)
    order_to = models.CharField(max_length=100, blank=True, null=True)
    order_from = models.CharField(max_length=100, blank=True, null=True)
    out_date_and_time = models.DateField(null=True, blank=True)
    prepared_by_name = models.CharField(max_length=100, blank=True, null=True)
    prepared_by_email = models.CharField(max_length=100, blank=True, null=True)
    poc_at_venue_name = models.CharField(max_length=100, blank=True, null=True)
    approver_email = models.CharField(max_length=100, blank=True, null=True)
    truck_details = models.CharField(max_length=100, blank=True, null=True)
    contact_details = models.CharField(max_length=100, blank=True, null=True)
    driver_details = models.CharField(max_length=100, blank=True, null=True)
    purpose = models.CharField(max_length=100, blank=True, null=True)
    reason = models.CharField(max_length=100, blank=True, null=True)
    office_address = models.CharField(max_length=100, blank=True, null=True)
    website = models.CharField(max_length=100, blank=True, null=True)
    challan_number = models.CharField(max_length=100, blank=True, null=True)
    maker_email = models.CharField(max_length=100, blank=True, null=True)
    checker_email = models.CharField(max_length=100, blank=True, null=True)
    

    approve_order = models.BooleanField(default=False)
    order_dispatch = models.BooleanField(default=False)


class OrderAttachFile(models.Model):
    order_id = models.ForeignKey(OrderDetail, on_delete= models.CASCADE)
    attached_file = models.FileField(upload_to="media/", default=None, null=True, blank=True)


class OrderComment(models.Model):
    order_id = models.ForeignKey(OrderDetail, on_delete= models.CASCADE)
    comment = models.CharField(max_length=100, null=True, blank=True)
    date_time = models.DateTimeField(auto_now=False, auto_now_add=False)






# class OrderTime(models.Model):
#      asset_id = models.ForeignKey(AssetMaster, on_delete=models.SET_NULL, null=True)
#      order_detail = models.ForeignKey(OrderDetail, on_delete=models.SET_NULL, null=True)
    


class OrderHistory(models.Model):

    order_id =models.ForeignKey(OrderDetail, on_delete=models.CASCADE)

    #Customer Details
    customer_id = models.IntegerField(null=True, blank=True)
    customer = models.CharField(max_length=100, blank=True, null=True)
    completed_orders = models.CharField(max_length=100, blank=True, null=True)
    deployed_order = models.CharField(max_length=100, blank=True, null=True)
    taxed = models.CharField(max_length=100, blank=True, null=True)
    email_address = models.CharField(max_length=100, blank=True, null=True)
    department = models.CharField(max_length=100, blank=True, null=True)
    phone_number = models.CharField(max_length=100, blank=True, null=True)
    customer_revenue = models.CharField(max_length=100, blank=True, null=True)
    commercial_address = models.CharField(max_length=100, blank=True, null=True)
    category = models.CharField(max_length=100, blank=True, null=True)
    created_at = models.DateField(null=True, blank=True, default=None)
    secondary_email = models.CharField(max_length=100, blank=True, null=True)
    description = models.CharField(max_length=100, blank=True, null=True)

orders/templates/asset_return_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Asset Availability Email</title>
</head>
<body>
    <p>Hi Zoom Communication Team,</p>
    <p>The order number "{{order_id}}" created by {{prepared_by_name}} with POC as “{{poc_at_venue_name}}” 
        is expected to return by “{{return_date}}”.</p>
    <p>“{{prepared_by_email}}” / “{{approver_email}}” - Please log-in to asset 
        master to make those assets available in inventory.</p>
    <p>Thanks,</p>
    <p>ERP Admin</p>
</body>
</html>

orders/templates/confirmed_orders_list.html
{% load static%}

{% include 'base_dashboard.html' %}
{% block content %}
<style>
    table {
            width: 100%;
            border-collapse: separate; /* Set border-collapse to separate */
            border-spacing: 0; /* Remove the space between cells */
            margin-top: 20px;
            border: 1px solid #F7EDFD;
            border-radius:10px ;

        }

        th, td {
            border: 1px solid #F7EDFD;
            padding: 8px;
            text-align: left;
        
        }
        .table thead th {
            border: none;
             color: #4C555D;
             font-size: 15px;
             font-weight: 600;
        }

        th {
            background-color: #F7EDFD;
            text-transform: uppercase;
            color: #4C555D;
            border: none; /* Remove border for th */
        }
        td {
            text-transform: capitalize;
            font-size: 14px;
        }

        /* Style for checkboxes */
        .checkbox-column {
            text-align: center;
        }
        th, td {
            border: none;
        }
        .assebutton{
            display: flex;
            gap: 10px;
        }
        td.tbname {
            color: #006FC8;
            text-transform:uppercase;
            text-decoration: none;
        }
        td.tbname a {
            text-decoration: none;
        }

        .pagination{
            float:right;
        }

        .select-button{
            border: 1px solid #CCCCCC;
            color: #7C7C7C !important;
            background-color: #FFFFFF;
            border-radius: 5px;
            padding: 0 6px;
            font-size: inherit;
            height:40px;
    
        }

        .asset-tablebtn button{
            border: 1px solid #CCCCCC;
            color: #7C7C7C !important;
            background-color: #FFFFFF;
            border-radius: 5px;
            padding: 0 20px;
            height: 40px;}

            span.select2-selection.select2-selection--single {
                height:38px !important;
            }
</style>

<!-- Alert JS -->
<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/alertify.min.css"/>
<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/themes/default.min.css"/>
<!-- Alert JS -->

<section class="assetdetail">
    <button onclick="goToDashboard()" style="border: none; margin-bottom: 10px; background-color: transparent;"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" style="fill: #6A1B9A;transform: ;msFilter:;"><path d="M12 2C6.486 2 2 6.486 2 12s4.486 10 10 10 10-4.486 10-10S17.514 2 12 2zm5 11h-5v4l-5-5 5-5v4h5v2z"></path></svg></button>

    <div class="assetheaderbuttones">
        <h1>Orders</h1>
        <div class="assebutton">
            <button ><a href="/asset_management/all-orders-list/" style="color: #fff; text-decoration: none;">Orders Cart</a></button>    
            {% comment %} <button ><a href="/asset_management/go-to-orders-history/" style="color: #fff; text-decoration: none;">Orders History</a></button>     {% endcomment %}
        </div>

    </div>
</section>
<!-- <div class="order-headingcnt">
    <h1>orders</h1>
</div> -->
<section class="assest-container-table">

    <div class="asset-tablebtn">
        <div class="searchiconbtn" >
            <form method="GET">   
                <input name="q" id="search_field" type="text" placeholder="Search.." value="{% if query_params_q %} {{query_params_q}} {% endif %}" style = "padding-left: 10px; border-radius: 5px;">   
                <select name="q" id="secondDropdown" name="second_dropdown" style="display: none; height:10%;">
                    <!-- The options will be populated dynamically -->
                </select>
                <select class='select-button' id="dropdown" name="filter_type">
                    <option  disabled {% if query_params_filter_value == '' or query_params_filter_value is None  %} selected {% endif %} value='none' >--Select--</option>
                    <option {% if query_params_filter_value == 'customer_id' %} selected {% endif %}  value="customer_id">Customer</option>
                    <option {% if query_params_filter_value == 'order_id' %} selected {% endif %} value="order_id">Order Number</option>
                </select>
                <button type='submit'>Search</button>
                <span><button onclick="clearSearch(event, 'search_field', 'dropdown', 'secondDropdown')">Clear</button></span>
            </form> 
        </div>
        <button id="exportButton">
            EXPORT TO CSV
        </button>
       

    </div>

    <table class="table">
        <thead>
            <tr>
                <th class="checkbox-column" style="border-radius: 10px 0 0 0;"><input type="checkbox" id="masterCheckbox" onclick="selectAllCheckboxes(this)"></th>
                <th>Order Number</th>
                <th>Customer </th>
                <th> Price</th>
                <th>Deployment Date</th>
                <th>Return Date</th>
                {% comment %} <th>Order Status</th> {% endcomment %}
                <!-- <th style="border-radius: 0 10px  0 0; cursor: pointer;"><img src="{% static 'images/sliders.svg' %}" alt=""></th> -->
            </tr>
        </thead>

        <tbody>
            {% for m in orders %}
            <tr>
                <td class="checkbox-column"><input type="checkbox" name="order_id" value="{{ m.id }}"></td>
                <td class="tbname"><a href="/asset_management/orders-info/{{m.id}}/">{{m.id}}</a></td>
                <td class="tbname"><a href="/asset_management/customer-details/{{m.customer_id.id}}/">{{m.customer_id.customer}}</a></td>
                <td>
                    {% if m.price == none or m.price == "" %}
                        --
                    {% else %}
                        {{m.price}}
                    {% endif %}
                </td>
                <td>
                    {% if m.deployment_date == none or m.deployment_date == "" %}
                        --
                    {% else %}
                        {{m.deployment_date|date:'d-m-Y'}}
                    {% endif %}
                </td>
                <td>
                    {% if m.return_date == none or m.return_date == "" %}
                        --
                    {% else %}
                        {{m.return_date|date:'d-m-Y'}}
                    {% endif %}
                </td>
               
                {% comment %} <td><div class="book-status">{{m.get_order_status_display}}</div></td>               {% endcomment %}

            </tr>
            {% endfor %}
            <!-- Add more rows as needed -->
        </tbody>
    </table>
    <div class="pagidis">
        <div></div>
    <div class="card text-center" style="border: none;">
            <div class="card-footer text-body-secondary" style="background-color: #fff; border: none;" >
            Displaying all {{queryset_length}} assets
            </div>
    </div>
    <div class="pagination">
        <span class="step-links">
            {% if orders.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ orders.previous_page_number }}">previous</a>
            {% endif %}
    
            <span class="current">
                Page {{ orders.number }} of  {{ orders.paginator.num_pages }}
            </span>
    
            {% if orders.has_next %}
                <a href="?page={{ orders.next_page_number }}">next</a>
                <a href="?page={{ orders.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
</div>
</section>
<script src="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/alertify.min.js"></script>

<script>
    {% if messages %}
        {% for msg in messages %}
            alertify.set('notifier','position', 'top-right');
            alertify.success('{{msg}}');
        {% endfor %}
    {% endif %}
</script>

<script>
    // JavaScript function to select or unselect all checkboxes
    function selectAllCheckboxes(masterCheckbox) {
        var checkboxes = document.querySelectorAll('tbody input[type="checkbox"]');
        checkboxes.forEach(function (checkbox) {
            checkbox.checked = masterCheckbox.checked;
        });
    }
</script>


<script>
    function clearSearch(event, mySearchField, dropdown, secondDropdown ) {
        event.preventDefault();
        document.getElementById(mySearchField).value=''; 
        document.getElementById(dropdown).value = 'none';
        document.getElementById(secondDropdown).value = '';
        $('#secondDropdown').empty().hide();
        $('#secondDropdown').append('<option value="">--Select--</option>');
        
    }
</script>



<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
$(document).ready(function() {
    
    $("#exportButton").on("click", function() {
        let spinner = ` <div id="spinner">
            <div class="d-flex justify-content-center">
                <div class="spinner-border" role="status">
                  <span class="visually-hidden"></span>
                </div>
              </div>
        </div> `
        $('#exportButton').html(spinner)

        // Selectes IDs
        var selectedAssetIds = $('input[name="order_id"]:checked').map(function() {
            return this.value;
        }).get();
        console.log(selectedAssetIds,"selectedAssetIds")

        $.ajax({
            type: "POST",
            url: "/asset_management/confirmed-order-export-to-csv/", 
            data: { selected_asset_ids: selectedAssetIds,
                "csrfmiddlewaretoken":"{{csrf_token}}" },
            success: function(data) {
                var blob = new Blob([data]);
                var link = document.createElement('a');
                link.href = window.URL.createObjectURL(blob);
                link.download = "Confirmed Order List.csv";
                link.click();
                window.location.reload()
            },
            error: function(xhr, status, error) {
                // console.error(error);
            }
        });
    });
});
</script>

<script>
    function goToDashboard(){
        window.location.href = '/'
    }
</script>



<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>
<script>
    $(document).ready(function() {
        $('#dropdown').change(function() {
            var selectedValue = $(this).val();
            if (selectedValue !== 'none') {
                $.ajax({
                    type: 'GET',
                    url: '/asset_management/confirm-order-search/', 
                    data: {
                        'selected_value': selectedValue
                    },
                    success: function(data) {
                        // Update the second dropdown with fetched data
                        $('#secondDropdown').empty().show();
                        $('#secondDropdown').append('<option value="">--Select--</option>');
                        $.each(data, function(key, value) {
                            $('#secondDropdown').append('<option value="' + value + '">' + value + '</option>');
                        });
                        $('#secondDropdown').select2({
                            placeholder: 'Search...',                             
                        });
                        $('#search_field').hide();
                        $('#secondDropdown').select2({
                            dropdownAutoWidth: true,
                            width:"300px",
                        });
                    },
                    error: function(xhr, status, error) {
                    }
                });
            } else {
                // If the default option is selected, hide the second dropdown and show the input dropdown
                $('#secondDropdown').hide();
                $('#search_field').show();
            }
        });
    });
</script>

{% endblock content %}